import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Character Basics',
      link: {type: 'doc', id: 'character-basics/index'},
      items: [
        'character-basics/create-a-character',
        'character-basics/design-a-scene',
        'character-basics/pick-a-voice',
        'character-basics/draw-animations',
        'character-basics/assemble-a-flow',
        'character-basics/view-in-chat',
      ],
    },
    {
      type: 'category',
      label: 'Posts',
      link: {type: 'doc', id: 'posts/index'},
      items: [
        'posts/release-calendar',
        'posts/post-formats',
        'posts/engagement-insights',
      ],
    },
    {
      type: 'category',
      label: 'GenAI',
      link: {type: 'doc', id: 'genai/index'},
      items: [
        'genai/prompting-fundamentals',
        'genai/workflow-automation',
        'genai/safety-and-qa',
      ],
    },
    {
      type: 'category',
      label: 'Subscription',
      link: {type: 'doc', id: 'subscription/index'},
      items: [
        'subscription/plans-and-benefits',
        'subscription/billing-and-payments',
        'subscription/team-management',
      ],
    },
  ],
  apiSidebar: [
    {
      type: 'doc',
      id: 'development/index',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'API',
      link: {
        type: 'generated-index',
        title: 'Drawhisper API',
        slug: '/development/api',
        description:
          'Learn how to integrate with the Drawhisper platform using our REST and webhook endpoints.',
      },
      items: [{type: 'autogenerated', dirName: 'development/api'}],
    },
  ],
};

export default sidebars;
